// <auto-generated />
namespace OrdBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TranslationDb2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TranslationDb2));
        
        string IMigrationMetadata.Id
        {
            get { return "201706210703062_TranslationDb2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
